# llm.py
import os
import google.generativeai as genai

# Read Gemini API key from env var
GEMINI_KEY = os.getenv("GEMINI_API_KEY", None)
if GEMINI_KEY is None:
    # if you prefer to hardcode for local testing, replace None with your key string here
    # GEMINI_KEY = "YOUR_KEY"
    raise RuntimeError("GEMINI_API_KEY not set. Set environment variable GEMINI_API_KEY before running.")

genai.configure(api_key=GEMINI_KEY)
MODEL_NAME = "gemini-2.5-flash"
model = genai.GenerativeModel(MODEL_NAME)

def synthesize_answer(query: str, contexts: list):
    """
    contexts: list of dicts each with 'text' and 'doc_id' optionally
    returns: a short synthesized answer string
    """
    # Keep context length modest: join top chunks
    ctx_text = "\n\n".join([f"(source: {c.get('doc_id','unknown')}) {c.get('text','')}" for c in contexts])
    prompt = f"""
You are a helpful technical assistant specialized in wind turbine maintenance.
Use the following context extracted from manuals to answer the user's question.
Context:
{ctx_text}

Question:
{query}

Answer concisely and clearly. If the context does not contain an answer, say you could not find a definitive answer in the provided documentation and suggest what the user should ask or check in the manual.
"""
    resp = model.generate_content(prompt)
    # extract text safely
    text = None
    if hasattr(resp, "text") and resp.text:
        text = resp.text
    else:
        # fallback to candidates
        try:
            cand = resp.candidates[0]
            if hasattr(cand, "content") and cand.content:
                parts = cand.content
                pieces = []
                for p in parts:
                    if hasattr(p, "parts"):
                        for sub in p.parts:
                            if hasattr(sub, "text") and sub.text:
                                pieces.append(sub.text)
                    elif isinstance(p, dict):
                        if "parts" in p:
                            for sub in p["parts"]:
                                if isinstance(sub, dict) and "text" in sub:
                                    pieces.append(sub["text"])
                        elif "text" in p:
                            pieces.append(p["text"])
                text = "\n".join(pieces)
        except Exception:
            text = None
    return text or "No answer generated by LLM."
